aws-list 0.9.2 - corrected problem in InstanceName retrieval significant speed boost by retrieving instance data with one query Modified Output Loop Structure. Structured script, added simple command-tail processor

diff --git a/aws-list b/aws-list
--- a/aws-list
+++ b/aws-list
@@ -6,71 +6,133 @@
 #          https://github.com/robertpeteuil/Easy-EC2
 #
 #  Author: Robert Peteuil   @RobertPeteuil
-# Version: 0.9.1, 2017-03-13
+#
 
+scriptname="aws-list"
+scriptbuildnum="0.9.2"
+scriptbuilddate="2017-03-13"
 
-# TURN ON COLOR IF POSSIBLE
+############################################################
+###     PRE-EXECUTION
+
+# TURN ON COLOR IF POSSIBLE, SET THEME
 if test -t 1; then            # check if stdout is a terminal
   ncolors=$(tput colors)    # see if it supports colors
   if test -n "$ncolors" && test $ncolors -ge 8; then
-    BLUE="\033[1;34m"
-    WHITE="\033[1;37m"
-    GREEN="\033[1;32m"
-    RED="\033[1;31m"
-    YELLOW="\033[1;33m"
-    CYAN="\033[1;36m"
+  # Set Colors
+    bold="$(tput bold)"
+    underline="$(tput smul)"
+    standout="$(tput smso)"
+    normal="$(tput sgr0)"
+    black="$(tput setaf 0)"
+    red="$(tput setaf 1)"
+    green="$(tput setaf 2)"
+    yellow="$(tput setaf 3)"
+    blue="$(tput setaf 4)"
+    magenta="$(tput setaf 5)"
+    cyan="$(tput setaf 6)"
+    white="$(tput setaf 7)"
+  # Set Color Theme - used by echo statements
+    CLRnormal=${bold}${white}
+    CLRheading=${bold}${green}
+    CLRheading2=${bold}${blue}
+    CLRtitle=${bold}${cyan}
+    CLRtitle2=${bold}${magenta}
+    CLRsuccess=${bold}${green}
+    CLRwarning=${bold}${yellow}
+    CLRerror=${bold}${red}
   fi
 fi
 
-ParamOne=$1
+############################################################
+### VAR INITS
 
 if [ -n "$AWS_DEFAULT_REGION" ]; then
-  OutputAddendum=" in ${BLUE}${AWS_DEFAULT_REGION}${WHITE}"
+  OutputAddendum=" in ${CLRheading2}${AWS_DEFAULT_REGION}${CLRnormal}"
 fi
 
-if [ "${ParamOne}" = "help" ] || [ "${ParamOne}" = "-h" ]; then
-  echo -e "lists status and information for AWS EC2 instances"
-  echo -e "\nusage: aws-list [OPTIONS]\n"
-  echo -e "\tOPTIONS"
-  echo -e "\t  (none) : list status of all instances"
-  echo -e "\t stopped : list status of stopped instances"
-  echo -e "\t running : list status of running instances"
+############################################################
+###   FUNCTIONS
+
+display_ver() {
+  echo -e "${CLRheading}${scriptname}${CLRnormal}  ver ${CLRtitle}${scriptbuildnum} ${CLRnormal}- ${CLRtitle}${scriptbuilddate}${CLRnormal}"
+}
+
+display_help_text() {
+  display_ver
+  echo
+  echo -e "${CLRtitle}lists status and information for AWS EC2 instances"
+  echo
+  echo -e "${CLRtitle}USAGE: ${CLRnormal}${scriptname} ${CLRtitle2}[OPTIONS]\n"
+  echo -e "${CLRtitle}OPTIONS:${CLRnormal}"
+  echo -e "${CLRtitle2} (none)\t${CLRnormal}: list status of all instances"
+  echo -e "${CLRtitle2}stopped\t${CLRnormal}: list status of stopped instances"
+  echo -e "${CLRtitle2}running\t${CLRnormal}: list status of running instances"
   echo
   exit 0
-elif [ "${ParamOne}" = "" ]; then
+}
+
+######################################################################
+###   EXECUTION STARTS HERE
+
+if [ "$1" = "" ]; then
   filters=""
   OutputText="EC2 Instances"
-elif [ "${ParamOne}" = "offline" ] || [ "${ParamOne}" = "stopped" ]; then
-  filters="--filters Name=instance-state-name,Values=stopped"
-  OutputText="Stopped EC2 Instances"
-elif [ "${ParamOne}" = "online" ] || [ "${ParamOne}" = "running" ]; then
-  filters="--filters Name=instance-state-name,Values=running"
-  OutputText="Running EC2 Instances"
 fi
 
-InstanceId=($(aws ec2 describe-instances ${filters} --query 'Reservations[*].Instances[].[InstanceId]' --output text))
-ImageAMI=($(aws ec2 describe-instances ${filters} --query 'Reservations[*].Instances[].[ImageId]' --output text))
-InstanceStatus=($(aws ec2 describe-instances ${filters} --query 'Reservations[*].Instances[].State[].[Name]' --output text))
+# Parse COMMAND-TAIL Arguments
+for arg in "$@"; do
+  case "$arg" in
+    offline|stopped)
+          filters="--filters Name=instance-state-name,Values=stopped"
+          OutputText="Stopped EC2 Instances"
+          shift ;;
+    online|running)
+          filters="--filters Name=instance-state-name,Values=running"
+          OutputText="Running EC2 Instances"
+          shift ;;
+    -h|--help)          display_help_text; exit ;;
+    -V|--version)       display_ver; exit ;;
+    -d|--debug)         debugmode=true; shift ;;
+    *)                  echo -e "invalid paramter\n";display_help_text; exit 1;;
+  esac
+done
 
-if [ ${#InstanceId[@]} -ne 0 ]; then
+# Get all instance data items
+InstanceData=($(aws ec2 describe-instances ${filters} --query 'Reservations[*].Instances[].[InstanceId,ImageId,State.Name,Tags[?Key==`Name`].Value]' --output text))
+
+numberDataRecords=4
+numberInstances=$(( ${#InstanceData[@]} / numberDataRecords ))
+
+[[ "$debugmode" ]] && echo -e "# instances found: $numberInstances \t total items collected: ${#InstanceData[@]}\t items per instance: $numberDataRecords\t "
+
+if [ ${#InstanceData[@]} -ne 0 ]; then
   echo -e "\n${OutputText}${OutputAddendum}:\n"
-  for (( i=0; i<"${#InstanceId[@]}"; i=i+1 )); do
-    InstanceName=$(aws ec2 describe-instances --instance-ids "${InstanceId[$i]}" --query 'Reservations[*].Instances[].Tags[].[Value,Key]' --output text)
-    InstanceName=$(echo $InstanceName | awk '/Name/ {print $1}')
-    ImageDescription=($(aws ec2 describe-images --image-ids ${ImageAMI[$i]} --query 'Images[*].{Name:Name}' --output text))
-    case ${InstanceStatus[$i]} in
-      running)  CLRstatus=${GREEN} ;;
-      stopped)  CLRstatus=${RED} ;;
-      stopping)  CLRstatus=${YELLOW} ;;
-      pending)  CLRstatus=${YELLOW} ;;
-      starting)  CLRstatus=${YELLOW} ;;
-      *)  CLRstatus=${WHITE} ;;
+
+  for (( j=0; j<${#InstanceData[@]}; j=j+$numberDataRecords )); do
+
+    InstanceId=${InstanceData[$j]}
+    ImageAMI=${InstanceData[$j+1]}
+    InstanceStatus=${InstanceData[$j+2]}
+    InstanceName=${InstanceData[$j+3]}
+
+    ImageDescription=($(aws ec2 describe-images --image-ids "${ImageAMI}" --query 'Images[*].{Name:Name}' --output text))
+
+    case ${InstanceStatus} in
+      running)    CLRstatus=${CLRsuccess} ;;
+      stopped)    CLRstatus=${CLRerror} ;;
+      stopping)   CLRstatus=${CLRwarning} ;;
+      pending)    CLRstatus=${CLRwarning} ;;
+      starting)   CLRstatus=${CLRwarning} ;;
+      *)          CLRstatus=${CLRnormal} ;;
     esac
-    echo -e "\t${WHITE}Name: ${CYAN}${InstanceName}${WHITE}     ID: ${CYAN}${InstanceId[$i]}${WHITE}     Status: ${CLRstatus}${InstanceStatus[$i]}"
-    echo -e "\t${WHITE}AMI: ${CYAN}${ImageAMI[$i]}${WHITE}     ${WHITE}AMI Name: ${CYAN}${ImageDescription}${WHITE}\n"
+    echo -e "\t${CLRnormal}Name: ${CLRtitle}${InstanceName}${CLRnormal}     ID: ${CLRtitle}${InstanceId}${CLRnormal}     Status: ${CLRstatus}${InstanceStatus}"
+    echo -e "\t${CLRnormal}AMI: ${CLRtitle}${ImageAMI}${CLRnormal}     ${CLRnormal}AMI Name: ${CLRtitle}${ImageDescription}${CLRnormal}\n"
+
   done
+
 else
-  echo -e "${RED}No ${OutputText} found${WHITE}"
+  echo -e "${CLRerror}No ${OutputText} found${CLRnormal}"
 fi
 
 exit 0
