Added Error Checking when Sourcing Init Files

diff --git a/utils/aws-ssh b/utils/aws-ssh
--- a/utils/aws-ssh
+++ b/utils/aws-ssh
@@ -9,11 +9,16 @@
 #
 
 scriptname="aws-ssh"
-scriptbuildnum="0.9.5.1"
+scriptbuildnum="0.9.5.2"
 scriptbuilddate="2017-04-10"
 
 # source aws-quick-cli init files to add color and display_ver function
-. aws-quick-cli-init.sh
+if [[ -e "aws-quick-cli-init.sh" ]]; then
+  . aws-quick-cli-init.sh
+else
+  echo "Error - required init files not found"
+  exit 1
+fi
 
 ############################################################
 ###   FUNCTIONS
